a = input('Digite algo:')
print('o tipo primitivo desse valor é', type(a))
print('só tem espaços?', a.isspace())
print('é um numero?',a.isnumeric())
print('é alfabetico?',a.isalpha())
print('é um alfanumerico?',a.isalnum())
print('esta em maiuscula?',a.isupper())
print('esta em  minusculo?',a.islower())
print('esta capitalizado?',a.istitle())
 